### ISSUE TITLE
adding new question keeps old multiple choice state

### ISSUE THREAD

**Issue by lexcooke** [ambivalent-acacia/ambivalent-acacia#240]

**Comment by m-sandusky** [comment]
For CreateEditQuestions.jsx, this.handleQuestionSubmission and this.cancelQuestion need to clear out the selected question state

**Comment by m-sandusky** [comment]
need to alter this.props.createQuestion()

**Comment by m-sandusky** [comment]
Change behavior in educatLoggedInActions.createQuestion
